version: "3"

services:
  postgres:
    container_name: cs452-postgres
    build:
      context: ./docker
    environment:
      POSTGRES_USER: cs452
      POSTGRES_PASSWORD: cs452
      POSTGRES_DB: cs452
      POSTGRES_AUTH_METHOD: trust
    ports:
      - "15432:5432"
    volumes:
      # - postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always

volumes:
  postgres:
    name: cs452-postgres
