version: "3"

services:
  postgres:
    container_name: natural-language-sql-database
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: cs452
      POSTGRES_PASSWORD: cs452
      POSTGRES_DB: cs452
      POSTGRES_AUTH_METHOD: trust
    ports:
      - "15432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always
