CREATE EXTENSION IF NOT EXISTS "pg_trgm" WITH SCHEMA "public";

-- CORE TYPES --

CREATE TABLE "user" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" character varying NOT NULL,
    "created_at" timestamp WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "tag" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" character varying NOT NULL
);

CREATE TABLE "post" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "artist" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "creator_id" bigint NOT NULL REFERENCES "user",
    "created_at" timestamp WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "pool" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" character varying NOT NULL,
    "creator_id" bigint NOT NULL REFERENCES "user",
    "created_at" timestamp WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

-- RELATIONSHIPS --

CREATE TABLE "artist_name" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "artist_id" bigint NOT NULL REFERENCES "artist" ON DELETE CASCADE,
    "name" character varying NOT NULL,
    "created_at" timestamp WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "artist_url" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "artist_id" bigint NOT NULL REFERENCES "artist" ON DELETE CASCADE,
    "url" text NOT NULL,
    "created_at" timestamp WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "pool_post" (
    "pool_id" bigint NOT NULL REFERENCES "pool" ON DELETE CASCADE,
    "post_id" bigint NOT NULL REFERENCES "post" ON DELETE CASCADE,
    PRIMARY KEY ("pool_id", "post_id")
);

CREATE TABLE "post_approval" (
    "user_id" bigint NOT NULL REFERENCES "user" ON DELETE CASCADE,
    "post_id" bigint NOT NULL REFERENCES "post" ON DELETE CASCADE,
    "created_at" timestamp WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("user_id", "post_id")
);

CREATE TABLE "post_disapproval" (
    "user_id" bigint NOT NULL REFERENCES "user" ON DELETE CASCADE,
    "post_id" bigint NOT NULL REFERENCES "post" ON DELETE CASCADE,
    "message" text,
    "created_at" timestamp WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("user_id", "post_id")
);

CREATE TABLE "post_comment" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "post_id" bigint NOT NULL REFERENCES "post" ON DELETE CASCADE,
    "user_id" bigint NOT NULL REFERENCES "user" ON DELETE CASCADE,
    "body" text NOT NULL,
    "created_at" timestamp WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "post_comment_vote" (
    "post_comment_id" bigint NOT NULL REFERENCES "post_comment" ON DELETE CASCADE,
    "user_id" bigint NOT NULL REFERENCES "user" ON DELETE CASCADE,
    "score" integer NOT NULL,
    "created_at" timestamp WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("post_comment_id", "user_id")
);

CREATE TABLE "post_favorite" (
    "post_id" bigint NOT NULL REFERENCES "post" ON DELETE CASCADE,
    "user_id" bigint NOT NULL REFERENCES "user" ON DELETE CASCADE,
    "created_at" timestamp WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    PRIMARY KEY ("post_id", "user_id")
);

CREATE TABLE "post_image" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "post_id" bigint NOT NULL REFERENCES "post" ON DELETE CASCADE
);

CREATE TABLE "post_tag" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "post_id" bigint NOT NULL REFERENCES "post" ON DELETE CASCADE,
    "tag_id" bigint NOT NULL REFERENCES "tag" ON DELETE CASCADE,
    "user_id" bigint NOT NULL REFERENCES "user" ON DELETE CASCADE,
    "created_at" timestamp WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "post_vote" (
    "post_id" bigint NOT NULL REFERENCES "post" ON DELETE CASCADE,
    "user_id" bigint NOT NULL REFERENCES "user" ON DELETE CASCADE,
    "score" integer NOT NULL,
    "created_at" timestamp WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("post_id", "user_id")
);

CREATE TABLE "tag_alias" (
    "antecedent_tag_id" bigint NOT NULL REFERENCES "tag" ON DELETE CASCADE,
    "consequent_tag_id" bigint NOT NULL REFERENCES "tag" ON DELETE CASCADE,
    PRIMARY KEY ("antecedent_tag_id", "consequent_tag_id"),
    CHECK ("antecedent_tag_id" <> "consequent_tag_id")
);

CREATE TABLE "tag_implication" (
    "antecedent_tag_id" bigint NOT NULL REFERENCES "tag" ON DELETE CASCADE,
    "consequent_tag_id" bigint NOT NULL REFERENCES "tag" ON DELETE CASCADE,
    PRIMARY KEY ("antecedent_tag_id", "consequent_tag_id"),
    CHECK ("antecedent_tag_id" <> "consequent_tag_id")
);

-- GENERATED DATA --

CREATE OR REPLACE VIEW "post_status" AS
SELECT
    "post"."id",
    COUNT("post_approval"."user_id") AS "approvals",
    COUNT("post_disapproval"."user_id") AS "disapprovals",
    COUNT("post_favorite"."user_id") AS "favorites",
    COUNT("post_vote"."user_id") AS "score"
FROM "post"
LEFT JOIN "post_approval" ON "post_approval"."post_id" = "post"."id"
LEFT JOIN "post_disapproval" ON "post_disapproval"."post_id" = "post"."id"
LEFT JOIN "post_favorite" ON "post_favorite"."post_id" = "post"."id"
LEFT JOIN "post_vote" ON "post_vote"."post_id" = "post"."id"
GROUP BY "post"."id";
